In [2]:
import numpy as np

### **1. Creating Arrays**
- **Question:** Write a NumPy code snippet to create a 2D array with values ranging from 1 to 9, arranged in 3 rows and 3 columns. Print the array and its shape.

In [ ]:

arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### **2. Converting between NumPy Arrays and Python Lists**
- **Question:** Convert the following Python list `[[1, 2, 3], [4, 5, 6]]` into a NumPy array. Then, convert it back into a Python list. Print both the NumPy array and the resulting list.

In [ ]:
array_from_list = np.array([[1, 2, 3], [4, 5, 6]])
list_from_array = array_from_list.tolist()
print("the array")
print(array_from_list)
print("the list")
print(list_from_array)


the array
[[1 2 3]
 [4 5 6]]
the list
[[1, 2, 3], [4, 5, 6]]


### **3. Array Attributes**
- **Question:** Given the NumPy array `array = np.array([[10, 20], [30, 40], [50, 60]])`, write a code snippet to print the array's `ndim`, `shape`, `size`, `dtype`, `itemsize`, and `nbytes` attributes.

In [ ]:
array = np.array([[10, 20], [30, 40], [50, 60]])
print(f"the array number of dimentoions is {array.ndim}")
print(f"the array shape is {array.shape}")
print(f"the array size or number of elements is {array.size}")
print(f"the array dtype or data type is {array.dtype}")
print(f"the array itemsize in byte is {array.itemsize}")

the array number of dimentoions is 2
the array shape is (3, 2)
the array size or number of elements is 6
the array dtype or data type is int64
the array itemsize in byte is 8



### **4. Indexing and Slicing**
- **Question:** Using the array `array = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])`, write code to extract and print the subarray containing the elements `[[8, 9], [11, 12]]`.


In [ ]:
array = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(array[:2,1:])

[[ 8  9]
 [11 12]]


### **5. Reshaping Arrays**
- **Question:** Reshape the array `array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])` into a 3x4 matrix and print the reshaped array and its new shape.

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_array = array.reshape(3,4)
print(new_array)
print(new_array.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


### **6. Broadcasting**
- **Question:** Add the 1D array `b = np.array([1, 2, 3])` to the 2D array `a = np.array([[4, 5, 6], [7, 8, 9]])` using broadcasting. Print the resulting array.

In [ ]:
b = np.array([1, 2, 3])
a = np.array([[4, 5, 6], [7, 8, 9]])
print("1D array b: \n", b)
print("2D array a: \n", a)
result = a + b
print("Result after broadcasting: \n", result)

1D array b: 
 [1 2 3]
2D array a: 
 [[4 5 6]
 [7 8 9]]
Result after broadcasting: 
 [[ 5  7  9]
 [ 8 10 12]]


### **7. Concatenating Arrays**
- **Question:** Concatenate the following two arrays `a = np.array([[1, 2], [3, 4]])` and `b = np.array([[5, 6], [7, 8]])` along the rows. Print the resulting array.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
concatonated_array = np.concatenate((a,b) , axis = 0)
print("the result concatonated array \n" , concatonated_array)

the result concatonated array 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]



### **8. Matrix Operations**
- **Question:** Perform element-wise multiplication on the matrices `a = np.array([[2, 4], [6, 8]])` and `b = np.array([[1, 3], [5, 7]])`. Print the resulting matrix.

In [ ]:
a = np.array([[2, 4], [6, 8]])
b = np.array([[1, 3], [5, 7]])
result = a * b
print("result of element wise multiplication \n ", result)

### **9. Universal Functions (ufuncs)**
- **Question:** Apply the sine function to the array `array = np.array([0, np.pi/2, np.pi])` using a universal function. Print the results.

In [ ]:
array = np.array([0, np.pi/2, np.pi])
result = np.sin(array)
print("the result of sine function \n", result)

the result of sine function 
 [0.0000000e+00 1.0000000e+00 1.2246468e-16]


### **10. Random Number Generation**
- **Question:** Write code to generate a 2x3 array of random integers between 10 and 50 using `np.random.randint`. Set a random seed for reproducibility. Print the generated array.

In [ ]:
np.random.seed(30)
array = np.random.randint(10,50,size=(2,3))
print("the randomly generated array \n"array)

[[47 47 22]
 [33 12 27]]



### **11. Array Flattening**
- **Question:** Given a 3D array `array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])`, flatten it into a 1D array. Then, reshape it back into a 3x4 array. Print both the flattened and reshaped arrays.

In [ ]:
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattend_array = array.flatten()
reshaped_array = flattend_array.reshape(3,4)
print("the flattend array \n", flattend_array)
print("the reshaped array \n", reshaped_array)

the flattend array 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
the reshaped array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



### **12. Matrix Determinant**
- **Question:** Create a 3x3 matrix using NumPy and calculate its determinant using the `np.linalg.det` function. Explain what the determinant signifies for this matrix.

In [ ]:
array = np.array([[4, 2, 3],
                  [3, 7, 1],
                  [10, 8, 9]])

determinant = np.linalg.det(array)

print("Matrix:\n", array)
print("Determinant:", determinant)
print("the Determinant meaning:")
if determinant != 0:
    print("- The matrix is not zero (non-singular), so it has an inverse (can be reversed).")
    print(f"- The matrix changes the size of things by a factor of {abs(determinant):.2f}.")
    if determinant > 0:
        print("- The matrix keeps the direction the same (no flipping).")
    else:
        print("- The matrix flips the direction.")
else:
    print("- The matrix is zero (singular), so it does not have an inverse.")
    print("- The matrix squashes things into a lower dimension (like a line or point).")

Matrix:
 [[ 4  2  3]
 [ 3  7  1]
 [10  8  9]]
Determinant: 48.00000000000001












### **13. Broadcasting and Arithmetic Operations**
- **Question:** Create a 3x3 matrix and a 1D array of length 3. Use broadcasting to subtract the 1D array from each row of the matrix. Then, use broadcasting again to multiply each column of the resulting matrix by a different scalar. Print the final matrix.

These questions offer a mix of foundational and advanced topics in NumPy, helping students deepen their understanding through practical coding exercises.

In [3]:
array_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
array_1d = np.array([4,2,6])
subtract_result = array_2d - array_1d
print("the result of subtracting \n" , subtract_result)
multiply_result = subtract_result * np.array([5,2,6])
print("the result of multiplying \n" , multiply_result)

the result of subtracting 
 [[-3  0 -3]
 [ 0  3  0]
 [ 3  6  3]]
the result of multiplying 
 [[-15   0 -18]
 [  0   6   0]
 [ 15  12  18]]
